from __future__ import annotations
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import importlib
import json
from datetime import datetime, timezone

from sos2026.paths import PROJECT_ROOT, STATUS_DIR, FIGURE_DIR, MOVIE_DIR, CACHE_DIR, ensure_directories

OPTIONAL = {
    "JAX": "jax",
    "vmec_jax": "vmec_jax",
    "booz_xform_jax": "booz_xform_jax",
    "NEO_JAX": "neo_jax",
    "sfincs_jax": "sfincs_jax",
    "SPECTRAX-GK": "spectrax",
    "SIMSOPT": "simsopt",
    "NEOPAX": "NEOPAX",
    "ESSOS": "essos",
}


def load_json(name, default):
    path = STATUS_DIR / name
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return default
    return default


def import_line(label, module):
    try:
        m = importlib.import_module(module)
        return f"- {label}: import OK (version {getattr(m, '__version__', 'unknown')}; module `{module}`)"
    except Exception as exc:
        return f"- {label}: import failed ({type(exc).__name__}: {exc}); cached/research-only path remains available"


def main() -> int:
    ensure_directories()
    smoke = load_json("smoke_tests.json", {})
    fetch = load_json("fetch_equilibria.json", [])
    figs = load_json("figures.json", {"figures": sorted(p.name for p in FIGURE_DIR.glob("*.png")), "count": len(list(FIGURE_DIR.glob("*.png")))})
    movies = load_json("movies.json", {"movies": sorted(p.name for p in MOVIE_DIR.glob("*.gif")), "results": []})
    notebooks = load_json("notebook_execution.json", [])

    lines = []
    lines.append("# STATUS")
    lines.append("")
    lines.append(f"Generated by `scripts/make_status_report.py` on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("This repository is ready for cached-mode teaching. Real scientific packages are optional and are documented as live, cached, or research-only below.")
    lines.append("")
    lines.append("## Package Import Status")
    lines.append("")
    for label, module in OPTIONAL.items():
        lines.append(import_line(label, module))
    lines.append("")
    lines.append("## Data Status")
    lines.append("")
    if fetch:
        for item in fetch:
            lines.append(f"- {item.get('label')}: {'OK' if item.get('ok') else 'FAIL'}; source={item.get('source')}; {item.get('message')}")
            if item.get("validation"):
                lines.append(f"  - validation: {item['validation']}")
    else:
        lines.append("- `scripts/fetch_equilibria.py --minimal` has not been run yet in this checkout.")
    lines.append("")
    lines.append("## Figure And Movie Status")
    lines.append("")
    lines.append(f"- Figures: {figs.get('count', len(figs.get('figures', [])))} PNG files in `assets/figures/`.")
    for name in figs.get("figures", [])[:30]:
        lines.append(f"  - `{name}`")
    lines.append(f"- Movies: {len(movies.get('movies', []))} GIF files in `assets/movies/`.")
    for item in movies.get("results", []):
        lines.append(f"  - {item.get('label')}: {'OK' if item.get('ok') else 'FAIL'}")
    lines.append("")
    lines.append("## Notebook Execution Status")
    lines.append("")
    if notebooks:
        for item in notebooks:
            lines.append(f"- `{item.get('name')}`: {'OK' if item.get('ok') else 'FAIL'}")
            if item.get("error"):
                lines.append(f"  - {item['error']}")
    else:
        lines.append("- Core notebooks have not been executed in this checkout yet.")
    lines.append("")
    lines.append("## Real-Code Demos")
    lines.append("")
    lines.append("- The environment check notebook imports installed optional packages when present.")
    lines.append("- `fetch_equilibria.py` uses real public HSX/W7-X VMEC files and a public SIMSOPT QA input when download or local public checkout succeeds.")
    lines.append("- Research-mode notebooks contain pointers for replacing cached arrays with `vmec_jax`, `booz_xform_jax`, `NEO_JAX`, `sfincs_jax`, `SPECTRAX-GK`, `NEOPAX`, `ESSOS`, or SIMSOPT runs.")
    lines.append("")
    lines.append("## Cached Or Synthetic Demos")
    lines.append("")
    for path in sorted(CACHE_DIR.glob("*")):
        if path.is_file():
            lines.append(f"- `{path.relative_to(PROJECT_ROOT)}`: cached educational fallback; not a new scientific prediction.")
    lines.append("")
    lines.append("## Known Limitations And Next Steps")
    lines.append("")
    lines.append("- Cached figures teach workflow shape and metric interpretation; they must not be cited as validated HSX or W7-X results.")
    lines.append("- Before the school, decide which optional packages to preinstall on the lecture machine and rerun the notebooks in `tiny` or `research` mode where feasible.")
    lines.append("- If live package APIs change, update `docs/code_stack.md` and the relevant notebook research-mode cells instead of weakening cached mode.")
    lines.append("- Source PDFs, PPTX files, zip files, and screenshots from the prompt package are intentionally excluded from git.")
    lines.append("")
    (PROJECT_ROOT / "STATUS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Updated STATUS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
