from __future__ import annotations
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import importlib
import json
from datetime import datetime, timezone

from sos2026.paths import PROJECT_ROOT, STATUS_DIR, FIGURE_DIR, MOVIE_DIR, CACHE_DIR, ensure_directories

OPTIONAL = {
    "JAX": "jax",
    "DESC": "desc",
    "vmec_jax": "vmec_jax",
    "booz_xform_jax": "booz_xform_jax",
    "NEO_JAX": "neo_jax",
    "SFINCS": "sfincs",
    "sfincs_jax": "sfincs_jax",
    "NTX": "ntx",
    "SPECTRAX-GK": "spectrax",
    "GX": "gx",
    "Trinity3D": "trinity3d",
    "SIMSOPT": "simsopt",
    "NEOPAX": "NEOPAX",
    "ESSOS": "essos",
    "KNOSOS": "knosos",
    "MONKES": "monkes",
}


def load_json(name, default):
    path = STATUS_DIR / name
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return default
    return default


def import_line(label, module):
    try:
        m = importlib.import_module(module)
        return f"- {label}: import OK (version {getattr(m, '__version__', 'unknown')}; module `{module}`)"
    except Exception as exc:
        return f"- {label}: import failed ({type(exc).__name__}: {exc}); cached/research-only path remains available"


def main() -> int:
    ensure_directories()
    smoke = load_json("smoke_tests.json", {})
    fetch = load_json("fetch_equilibria.json", [])
    figs = load_json("figures.json", {"figures": sorted(p.name for p in FIGURE_DIR.glob("*.png")), "count": len(list(FIGURE_DIR.glob("*.png")))})
    movies = load_json("movies.json", {"movies": sorted(p.name for p in MOVIE_DIR.glob("*.gif")), "results": []})
    notebooks = load_json("notebook_execution.json", [])
    notebooks_all = load_json("notebook_execution_all.json", [])
    notebooks_in_place = load_json("notebook_execution_in_place.json", [])
    notebook_audit = load_json("notebook_output_audit.json", [])
    powerpoint = load_json("powerpoint_decks.json", {})

    lines = []
    lines.append("# STATUS")
    lines.append("")
    lines.append(f"Generated by `scripts/make_status_report.py` on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("This repository is ready for cached-mode teaching. Real scientific packages are optional and are documented as live, cached, or research-only below.")
    lines.append("")
    lines.append("Provenance categories used below: `real public data`, `real package output`, `cached derived data`, `synthetic educational fallback`, and `reference slide extract`.")
    lines.append("")
    lines.append("## Package Import Status")
    lines.append("")
    for label, module in OPTIONAL.items():
        lines.append(import_line(label, module))
    lines.append("")
    lines.append("## Data Status")
    lines.append("")
    if fetch:
        for item in fetch:
            category = item.get("category", "real public data" if item.get("ok") else "unknown")
            lines.append(f"- {item.get('label')}: {'OK' if item.get('ok') else 'FAIL'}; category={category}; source={item.get('source')}; {item.get('message')}")
            if item.get("validation"):
                lines.append(f"  - validation: {item['validation']}")
            if item.get("sha256"):
                lines.append(f"  - sha256: `{item['sha256'][:16]}...`")
    else:
        lines.append("- `scripts/fetch_equilibria.py --minimal` has not been run yet in this checkout.")
    lines.append("")
    lines.append("## Figure And Movie Status")
    lines.append("")
    lines.append(f"- Figures: {figs.get('count', len(figs.get('figures', [])))} PNG files in `assets/figures/`.")
    if figs.get("manifest"):
        lines.append(f"  - manifest: `{figs['manifest']}`")
    figure_names = figs.get("figures", [])
    for name in figure_names[:30]:
        lines.append(f"  - `{name}`")
    if len(figure_names) > 30:
        lines.append(f"  - plus {len(figure_names) - 30} more; see `assets/figures/manifest.json` for full provenance.")
    lines.append(f"- Movies: {len(movies.get('movies', []))} GIF files in `assets/movies/`.")
    for item in movies.get("results", []):
        first_frame = item.get("first_frame")
        if first_frame:
            first_frame = Path(first_frame)
            if first_frame.is_absolute() and first_frame.exists():
                first_frame = first_frame.relative_to(PROJECT_ROOT)
        lines.append(f"  - {item.get('label')}: {'OK' if item.get('ok') else 'FAIL'}; category={item.get('category', 'synthetic educational fallback')}; first frame `{first_frame}`")
    lines.append("")
    lines.append("## Notebook Execution Status")
    lines.append("")
    if notebooks:
        lines.append("Core acceptance notebooks:")
        for item in notebooks:
            lines.append(f"- `{item.get('name')}`: {'OK' if item.get('ok') else 'FAIL'}")
            if item.get("error"):
                lines.append(f"  - {item['error']}")
    else:
        lines.append("- Core notebooks have not been executed in this checkout yet.")
    if notebooks_all:
        lines.append("")
        lines.append("All teaching notebooks:")
        for item in notebooks_all:
            lines.append(f"- `{item.get('name')}`: {'OK' if item.get('ok') else 'FAIL'}")
            if item.get("error"):
                lines.append(f"  - {item['error']}")
    if notebooks_in_place:
        lines.append("")
        lines.append("Committed notebooks with rendered outputs:")
        for item in notebooks_in_place:
            output_count = item.get("outputs", 0)
            lines.append(f"- `{item.get('name')}`: {'OK' if item.get('ok') else 'FAIL'}; {output_count} output objects saved in-place")
            if item.get("error"):
                lines.append(f"  - {item['error']}")
    if notebook_audit:
        lines.append("")
        lines.append("Notebook output audit:")
        for item in notebook_audit:
            lines.append(
                f"- `{item.get('name')}`: {'OK' if item.get('ok') else 'FAIL'}; "
                f"{item.get('output_cells')} cells with outputs; {item.get('rich_outputs')} plot/table-rich outputs"
            )
            for error in item.get("errors", []):
                lines.append(f"  - cell {error.get('cell')}: {error.get('ename')}: {error.get('evalue')}")
    lines.append("")
    lines.append("## PowerPoint Deck Status")
    lines.append("")
    decks = powerpoint.get("decks", []) if isinstance(powerpoint, dict) else []
    if decks:
        for deck in decks:
            output = Path(deck.get("output", ""))
            contact = Path(deck.get("contactSheet", ""))
            output_label = output.relative_to(PROJECT_ROOT) if output.is_absolute() and output.exists() else output
            contact_label = contact.relative_to(PROJECT_ROOT) if contact.is_absolute() and contact.exists() else contact
            lines.append(
                f"- `{deck.get('id')}`: {deck.get('slideCount')} slides; "
                f"PPTX `{output_label}`; contact sheet `{contact_label}`; "
                f"{deck.get('outputBytes')} bytes."
            )
    else:
        pptx_files = sorted((PROJECT_ROOT / "slides" / "pptx").glob("*.pptx"))
        if pptx_files:
            for path in pptx_files:
                lines.append(f"- `{path.relative_to(PROJECT_ROOT)}`: PPTX present ({path.stat().st_size} bytes).")
        else:
            lines.append("- PowerPoint decks have not been generated in this checkout yet.")
    lines.append("")
    lines.append("## Real-Code Demos")
    lines.append("")
    lines.append("- The environment check notebook imports installed optional packages when present.")
    lines.append("- `fetch_equilibria.py` uses real public HSX/W7-X VMEC files and a public SIMSOPT QA input when download succeeds or when an instructor opts into `SOS2026_PUBLIC_CHECKOUT_ROOT`.")
    lines.append("- Research-mode notebooks contain pointers for replacing cached arrays with VMEC/DESC equilibrium paths, `vmec_jax`, `booz_xform_jax`, `NEO_JAX`, SFINCS/`sfincs_jax`, NTX, GX/`SPECTRAX-GK`, `NEOPAX`, `ESSOS`, or SIMSOPT runs where the package and inputs are available.")
    lines.append("- No notebook claims a new real package output unless that package path is explicitly executed in `research` mode.")
    lines.append("")
    lines.append("## Cached Or Synthetic Demos")
    lines.append("")
    for path in sorted(CACHE_DIR.glob("*")):
        if path.is_file():
            lines.append(f"- `{path.relative_to(PROJECT_ROOT)}`: cached derived data or synthetic educational fallback; not a new scientific prediction.")
    lines.append("")
    lines.append("## Known Limitations And Next Steps")
    lines.append("")
    lines.append("- Cached figures teach workflow shape and metric interpretation; they must not be cited as validated HSX or W7-X results.")
    lines.append("- Before the school, decide which optional packages to preinstall on the lecture machine and rerun the notebooks in `tiny` or `research` mode where feasible.")
    lines.append("- If live package APIs change, update `docs/code_stack.md` and the relevant notebook research-mode cells instead of weakening cached mode.")
    lines.append("- Source PDFs, PPTX files, zip files, and screenshots from the prompt package are intentionally excluded from git.")
    lines.append("")
    (PROJECT_ROOT / "STATUS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Updated STATUS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
